### PR TITLE
data_composition_plot

### PR DESCRIPTION
**Pull request by ScottSu0114**

### CODE REVIEW

**Comment by alexandriaGuo** [comment]
@jtr13 should all labels on R chunks be removed, to be safe?

**Comment by jtr13** [comment]
I don't think that's necessary but no harm to at least remove `cars` and `pressure` which clearly shouldn't be there. Note that this PR wasn't submitted from a new branch so it needs to be resubmitted.

**Comment by alexandriaGuo** [comment]
@ScottSu0114 please resubmit from a new branch, not main, and remove the r chunk labels "car" and "'pressure"

**Comment by alexandriaGuo** [comment]
@ScottSu0114 please make the changes requested above -- if you need any help, please let me know!

**Comment by alexandriaGuo** [comment]
@ScottSu0114 if you need any help making the changes, please @ me

**Comment by ScottSu0114** [comment]
@alexandriaGuo Hi, I think r chunk labels "car" and "'pressure" should not be removed because we need to use it for making plots.

**Comment by ScottSu0114** [comment]
@alexandriaGuo Also, I created a new branch called data_composition but Github told me the new branch are identical with the main branch of jtr13:main

**Pull request closed without merging**
