### PR TITLE
Community Contribution - MTemplates (New Package) - mj3038

### PR DESCRIPTION
**Pull request by maheshjindal**

### CODE REVIEW

**Review by alexnsaunders — CHANGES_REQUESTED** [review]

**Comment by maheshjindal** [comment]
Hi @alexnsaunders, I have made the suggested changes and updated the PR. Please let me know in case of any issues.

**Review by alexnsaunders — APPROVED** [review]
Thanks! Looks good!

**Comment by alexnsaunders** [comment]
thanks!! 🎉

**Comment by alexnsaunders** [comment]
https://jtr13.github.io/cc21fall2/mtemplates.html 🎉 done and rendered!

**Pull request merged**
