### PR TITLE
Map Visualization with R tutorial

### PR DESCRIPTION
**Pull request by UlisesHdzG**
Add Map Visualization with R

### CODE REVIEW

**Comment by rao53** [comment]
Thank you for your contribution!

**Comment by rao53** [comment]
@jtr13, the bookdown file failed due to: "Error in library(spDataLarge) : there is no package called 'spDataLarge". Should I follow up with the student? I'm not sure how to approach this given that it seems to be a valid library when I google it.

**Comment by jtr13** [comment]
You can add the package to the DESCRIPTION file. (I tried to add all the packages from the community contributions in advance but I didn't get them all.)

**Comment by rao53** [comment]
> You can add the package to the DESCRIPTION file. (I tried to add all the packages from the community contributions in advance but I didn't get them all.)

For some reason, it's still failing even after adding the package to the description file. @jtr13

**Comment by UlisesHdzG** [comment]
Hi!

I just noticed that the package that is failling is not used in the project. I forgot to delete that line of code. How can I update the file?

Sorry for the inconvenients. 

Ulises.

**Comment by rao53** [comment]
I can fix that no worries.

**Comment by UlisesHdzG** [comment]
Thanks!!!

**Comment by rao53** [comment]
Just to clarify, it is only the "spDataLarge" package right?

**Comment by UlisesHdzG** [comment]
Yes. Only "spDataLarge" package.

**Comment by jtr13** [comment]
I'm going to delete that package from DESCRIPTION.

**Comment by rao53** [comment]
I deleted it already.

**Comment by jtr13** [comment]
It was still there 10 minutes ago.

**Pull request merged**
