### PR TITLE
use python in r

### PR DESCRIPTION
**Pull request by lulululuxingyu**

### CODE REVIEW

**Comment by lulululuxingyu** [comment]
Xingyu Lu, xl3132, community contribution

**Comment by Gangadharareddy514** [comment]
The .Rmd filename should only contain lowercase letters.
No Single Hashtags are allowed in the file except in the first line. Please fix them.

**Comment by Gangadharareddy514** [comment]
Changes_required
Rmd filename is still not in Lower Case letters.

**Comment by Gangadharareddy514** [comment]
Thank you for your contribution 🎉

**Pull request merged**
