### PR TITLE
add intro to log transformation rmd

### PR DESCRIPTION
**Pull request by jyjuni**
this is our cheatsheat for 5702 cc project

### CODE REVIEW

**Review by AdrianGarciaH — CHANGES_REQUESTED** [review]
Please fix it according to the comments and resubmit.

**Comment by AdrianGarciaH** [comment]
@jyjuni just reminding you to please correct the issues.

**Comment by jyjuni** [comment]
> @jyjuni just reminding you to please correct the issues.

thanks! I just found the conflict file and resolved it. Please check.

**Comment by AdrianGarciaH** [comment]
Thanks! Just merged 🎉

**Pull request merged**
