### PR TITLE
3 d data and potential relationship visualization

### PR DESCRIPTION
**Pull request by yinghao11**
First submit

### CODE REVIEW

**Comment by pyropig** [comment]
which one is your file? You're commiting change to everyone else's file in the repo and I can't find yours to give a label on

**Comment by yinghao11** [comment]
Hi, "3D_data_and_potential_relationship_visualization.Rmd“ is my file and the only one I changed. The rest I just pulled from the remote repo. Thanks

**Comment by pyropig** [comment]
You can look at the "file changed" page on your pull request showing there's 32 files in total you are changeing.

**Comment by yinghao11** [comment]
Sure, I am aware now. It seems due to I copy all files to the new branch.
So what should I do?

Best,
Yinghao

**Comment by jtr13** [comment]
All of the previous files always are part of the new branch. The issue is that it is saying that you changed them. However it doesn't like you did, so let's proceed as usual. I resolved the conflicts in the 3 files that were showing them.

**Comment by yinghao11** [comment]
Thanks!

Have a nice day!

**Comment by alexnsaunders** [comment]
@pyropig @sarthak-arora1997 Looks like we can merge this (I mean I haven't checked the actual files myself but from the comments) - who is doing this one or did it fall through the cracks?

**Comment by sarthak-arora1997** [comment]
it still shows 32 files changed, it seems like we still have merged conflicts with core files including description and bookdown.yaml along with some other files as well. how should i proceed further ?

**Comment by jtr13** [comment]
Thanks for your contribution and apologies for the delay!

**Pull request merged**
