### PR TITLE
Running Sql Queries on Dataframes (Community contribution Group 11).

### PR DESCRIPTION
**Pull request by ksdkalluri**

### CODE REVIEW

**Comment by Gangadharareddy514** [comment]
Hashtags should not be present in the file except in the first line. please fix it.

**Comment by ksdkalluri** [comment]
> Single Hashtags should not be present in the file except in the first line. please fix it.

Updated the Headings, let me know if there is anything that needs to be fixed. Thanks!

**Comment by ksdkalluri** [comment]
> > Single Hashtags should not be present in the file except in the first line. please fix it.
> 
> Updated the Headings, let me know if there is anything that needs to be fixed. Thanks!

@Gangadharareddy514 Is there anything we are missing in this PR? curious to know why it's not approved or merged yet.

**Comment by Gangadharareddy514** [comment]
Screenshot 2021-11-10 at 12 19 43 AM
I dont have write access to your bookdown.yml file so i am not able to edit it. Please give me the write access.

**Comment by ksdkalluri** [comment]
> Screenshot 2021-11-10 at 12 19 43 AM
> 
> I dont have write access to your bookdown.yml file so i am not able to edit it. Please give me the write access.

@Gangadharareddy514 Done sent you an invite giving you write access to the repository.

**Comment by Gangadharareddy514** [comment]
Thank you for your contribution 🎉

**Comment by jtr13** [comment]
@Gangadharareddy514 
1. Please use descriptive commit messages even when you're updating _bookdown.yml
2. This build failed (https://github.com/jtr13/cc21fall2/actions/runs/1446360938) Please open an issue explaining what the problem is which you can find in the log.

**Pull request merged**
