### PR TITLE
updated Yuren's Rmd

### PR DESCRIPTION
**Pull request by yunyuntian**

### CODE REVIEW

**Comment by alexnsaunders** [comment]
Thanks - file looks good - not sure if it should just be a github link, won't it just render as hyperlink though ? checking with @jtr13 @Abhimanyu210100. If ok then I think I can merge

**Comment by jtr13** [comment]
Yes, it should work as is... good to go! 🚀

**Comment by alexnsaunders** [comment]
@jtr13 @Abhimanyu210100 Not related to this file which looks ok but I got a book error when it was merged and pushed. Looks like the bookdown_yml file has a reference to make_r_package_cheatsheet.Rmd that doesn't exist. I don't *think* it was to do with my commit - let me know if you want me to edit and take out errant reference. Alex

**Comment by alexnsaunders** [comment]
Here is your chapter - congrats https://jtr13.github.io/cc21fall2/how-to-make-your-own-r-package.html

**Pull request merged**
