### PR TITLE
Update scatterplots_cheatsheet.Rmd

### PR DESCRIPTION
**Pull request by ShangzhiLiu2021**
I add a link to my scatterplots cheatsheet pdf file.

### CODE REVIEW

**Comment by AdrianGarciaH** [comment]
@ShangzhiLiu2021  you did not include a title in the rmd file as specified in the interactions. please correct.

**Comment by ShangzhiLiu2021** [comment]
I think the first line is my title, which is "# Scatterplots cheatsheet".
Actually my original pull request  #63 has been merged. It is Chapter #38 Scatterplots cheatsheet. However, in my original Rmd file, I forgot to add the link to my cheatsheet Pdf file. In this new pull request, I want to add the link to update my Rmd file.

**Comment by AdrianGarciaH** [comment]
@ShangzhiLiu2021  apologies i totally missed that line! Just merged your updated file! 🎉

**Comment by ShangzhiLiu2021** [comment]
Thank you!

**Pull request merged**
