### PR TITLE
neo4j python implementation by yc4007

### PR DESCRIPTION
**Pull request by yc4007**
Neo4j python implementation tutorial by yc4007

### CODE REVIEW

**Comment by pyropig** [comment]
Will .py file be rendered properly in the Github bookdown? I thought it should be all .rmd files...
@jtr13

**Comment by jtr13** [comment]
No, it won't work. They need to submit an .Rmd file. It can be short and link to Python code on another repo for example.

**Review by nicric99 — CHANGES_REQUESTED** [review]
You have to submit an .Rmd file following all the rules for GitHub.

**Comment by nicric99** [comment]
@yc4007 Please follow the instructions and submit the work

**Comment by nicric99** [comment]
@jtr13 the student is not answering

**Comment by yc4007** [comment]
I have opened a different branch called py2neo for my work.

**Comment by jtr13** [comment]
Closing this PR since it was resubmitted #96

**Pull request closed without merging**
