### PR TITLE
data_vis_for_ranking

### PR DESCRIPTION
**Pull request by ling76583**
initial commitment

### CODE REVIEW

**Comment by ling76583** [comment]
Tutorial ls3759 jc5530

**Comment by Abhimanyu210100** [comment]
@ling76583 can you please confirm that you received my comment and make appropriate changes to your submission

**Comment by ling76583** [comment]
> @ling76583 can you please confirm that you received my comment and make appropriate changes to your submission

I am not very clear what else I need to do about my submission. Could you please explain a bit more? Thank you!

**Comment by Abhimanyu210100** [comment]
@ling76583 The first line of your .RMD file contains two '#'. The first line should contain only a single '#'. 

That is change '##Data visualization for ranking in R' to '#Data visualization for ranking in R'

**Comment by ling76583** [comment]
Thanks for explanation. I have changed the first line of the .RMD file.

**Comment by Abhimanyu210100** [comment]
Thank you for your contribution 🎉

**Pull request merged**
