### PR TITLE
Create video tutorial about apply function in R

### PR DESCRIPTION
**Pull request by TianmaiJiao**
Here is my community contribution for EDAV Tues/Thurs section.

### CODE REVIEW

**Comment by HannahFromAland** [comment]
@jtr13 Hi prof. Robbins, I just tried to check and resolve the conflits in this branch (to get myself more familiar with the process :). Could you please check whether there exists any other question before merging? Thank you very much! 😆

**Comment by jtr13** [comment]
@HannahFromAland Looks great!

**Comment by HannahFromAland** [comment]
Thank you for your contribution! 🎉

**Comment by jtr13** [comment]
Your chapter is now published: https://jtr13.github.io/cc21fall2/apply-function-in-r.html 🚀

**Comment by TianmaiJiao** [comment]
> Your chapter is now published: https://jtr13.github.io/cc21fall2/apply-function-in-r.html 🚀

Thank you!

**Pull request merged**
